/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package glfood;

import static glfood.payment.conn;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.sql.Statement;
import java.net.Socket;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ACER
 */
public class changepassword extends javax.swing.JFrame {

    /**
     * Creates new form changepassword
     */
    boolean a = true;
    boolean b = true;
    ChatMessageSocket mSocket;
    private javax.swing.JTextPane display;
    static Connection conn;
    static PreparedStatement prs;
    static ResultSet rs;

    public changepassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        currentpass = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        newpass = new javax.swing.JLabel();
        newpassField = new javax.swing.JPasswordField();
        confirmpass = new javax.swing.JLabel();
        confirmField = new javax.swing.JPasswordField();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        header2 = new javax.swing.JPanel();
        phonenumber = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        currentpass.setForeground(new java.awt.Color(51, 51, 51));
        currentpass.setText("Current password");
        background.add(currentpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 130, 20));

        passwordfield.setText("jPasswordField1");
        background.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 200, -1));

        newpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newpass.setForeground(new java.awt.Color(51, 51, 51));
        newpass.setText("New password");
        background.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 130, 20));

        newpassField.setText("jPasswordField1");
        background.add(newpassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 200, -1));

        confirmpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmpass.setForeground(new java.awt.Color(51, 51, 51));
        confirmpass.setText("Confirm new password");
        background.add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 170, 20));

        confirmField.setText("jPasswordField1");
        background.add(confirmField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, -1));

        ok.setBackground(new java.awt.Color(255, 102, 51));
        ok.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ok.setForeground(new java.awt.Color(255, 255, 255));
        ok.setText("OK");
        ok.setOpaque(true);
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });
        background.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 100, 30));

        cancel.setBackground(new java.awt.Color(255, 102, 51));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.setOpaque(true);
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        background.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 100, 30));

        header2.setBackground(new java.awt.Color(255, 102, 51));
        header2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 50));

        phonenumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phonenumber.setForeground(new java.awt.Color(51, 51, 51));
        phonenumber.setText("Phone Number");
        background.add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 130, 20));
        background.add(jTextFieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 200, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked

        if (newpassField.getText().equals(confirmField.getText())) {
            edit();
        } else {
            JOptionPane.showMessageDialog(this, "New password does not match. Please confirm the new password again");
        }
    }//GEN-LAST:event_okMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        dispose();
        FoodHomePage food = new FoodHomePage();
        food.setVisible(true);
        food.setLocationRelativeTo(null);
    }//GEN-LAST:event_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void connect() {
        try {
            String sqlServer = "jdbc:sqlserver://LAPTOP-EUQVAG1I\\SQLEXPRESS;databasename=GLFood;user=sa;password=123456789";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection(sqlServer);
            Statement stm = conn.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public int executeDB(String sql) {
        int record = 0;// number of records have been changed in db
        try {
            connect();
            Statement stmt = conn.createStatement();
            record = stmt.executeUpdate(sql);
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
        }
        return record;
    }

    public void edit() {
        try {

            String sql = "UPDATE AccountGL SET Password = '" + newpassField.getText() + "' WHERE Password = '" + jTextFieldPhone.getText() + "'";

            int record = executeDB(sql);

            if (record > 0) {
                JOptionPane.showMessageDialog(null, "Success");
            }

        } catch (Exception e2) {
            JOptionPane.showMessageDialog(null, "Unable to change password at this time");
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                changepassword change = new changepassword();
                change.setVisible(true);
                change.setLocationRelativeTo(null);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton cancel;
    private javax.swing.JPasswordField confirmField;
    private javax.swing.JLabel confirmpass;
    private javax.swing.JLabel currentpass;
    private javax.swing.JPanel header2;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JLabel newpass;
    private javax.swing.JPasswordField newpassField;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel phonenumber;
    // End of variables declaration//GEN-END:variables
}
