/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package glfood;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.sql.Statement;
import java.net.Socket;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ACER
 */
public class FoodHomePage extends javax.swing.JFrame {

    /**
     * Creates new form FoodMenu
     */
    boolean a = true;
    boolean b = true;
    ChatMessageSocket mSocket;
    private javax.swing.JTextPane display;
    static Connection conn;
    static PreparedStatement prs;
    static ResultSet rs;

    public FoodHomePage() {
        initComponents();
        heart1();
        heart2();
        heart3();
        heart4();
        heart5();
        heart6();
        heart7();
        heart8();
        heart9();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        linehidenmenu = new javax.swing.JPanel();
        hidenmenu = new javax.swing.JPanel();
        buttonhidenmenu = new javax.swing.JLabel();
        setting = new javax.swing.JPanel();
        buttonsetting = new javax.swing.JLabel();
        linesetting = new javax.swing.JPanel();
        linechat = new javax.swing.JPanel();
        buttonhidenmenu2 = new javax.swing.JLabel();
        menuhide = new javax.swing.JPanel();
        contact = new javax.swing.JLabel();
        gomenu = new javax.swing.JLabel();
        homepage = new javax.swing.JLabel();
        cart = new javax.swing.JLabel();
        favor = new javax.swing.JLabel();
        sett = new javax.swing.JPanel();
        menuIcon1 = new javax.swing.JPanel();
        linehidenmenu1 = new javax.swing.JPanel();
        hidenmenu1 = new javax.swing.JPanel();
        buttonhidenmenu1 = new javax.swing.JLabel();
        setting1 = new javax.swing.JPanel();
        buttonsetting1 = new javax.swing.JLabel();
        linesetting1 = new javax.swing.JPanel();
        menuhide1 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        header2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listfood = new javax.swing.JPanel();
        listproduct = new javax.swing.JScrollPane();
        product = new javax.swing.JPanel();
        food9 = new javax.swing.JPanel();
        foodpic9 = new javax.swing.JLabel();
        namefood9 = new javax.swing.JLabel();
        heart8 = new javax.swing.JLabel();
        cost8 = new javax.swing.JLabel();
        food8 = new javax.swing.JPanel();
        foodpic8 = new javax.swing.JLabel();
        namefood8 = new javax.swing.JLabel();
        heart7 = new javax.swing.JLabel();
        cost7 = new javax.swing.JLabel();
        food7 = new javax.swing.JPanel();
        foodpic7 = new javax.swing.JLabel();
        namefood7 = new javax.swing.JLabel();
        heart6 = new javax.swing.JLabel();
        cost6 = new javax.swing.JLabel();
        food6 = new javax.swing.JPanel();
        foodpic6 = new javax.swing.JLabel();
        namefood6 = new javax.swing.JLabel();
        heart5 = new javax.swing.JLabel();
        cost5 = new javax.swing.JLabel();
        food5 = new javax.swing.JPanel();
        foodpic5 = new javax.swing.JLabel();
        namefood5 = new javax.swing.JLabel();
        heart4 = new javax.swing.JLabel();
        cost4 = new javax.swing.JLabel();
        food4 = new javax.swing.JPanel();
        foodpic4 = new javax.swing.JLabel();
        namefood4 = new javax.swing.JLabel();
        heart3 = new javax.swing.JLabel();
        cost3 = new javax.swing.JLabel();
        food3 = new javax.swing.JPanel();
        foodpic3 = new javax.swing.JLabel();
        namefood3 = new javax.swing.JLabel();
        heart2 = new javax.swing.JLabel();
        cost2 = new javax.swing.JLabel();
        food2 = new javax.swing.JPanel();
        foodpic2 = new javax.swing.JLabel();
        namefood2 = new javax.swing.JLabel();
        heart1 = new javax.swing.JLabel();
        cost1 = new javax.swing.JLabel();
        food1 = new javax.swing.JPanel();
        foodpic1 = new javax.swing.JLabel();
        namefood1 = new javax.swing.JLabel();
        foodname2 = new javax.swing.JLabel();
        heart = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        header3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        graphics = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        picgrap1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dashboardview = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(770, 615));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setPreferredSize(new java.awt.Dimension(50, 580));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuIcon.setBackground(new java.awt.Color(255, 102, 51));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehidenmenu.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout linehidenmenuLayout = new javax.swing.GroupLayout(linehidenmenu);
        linehidenmenu.setLayout(linehidenmenuLayout);
        linehidenmenuLayout.setHorizontalGroup(
            linehidenmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehidenmenuLayout.setVerticalGroup(
            linehidenmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon.add(linehidenmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 10));

        hidenmenu.setBackground(new java.awt.Color(255, 102, 51));
        hidenmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonhidenmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidenmenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\PinClipart.com_cempasuchil-clipart_1812493.png")); // NOI18N
        buttonhidenmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidenmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidenmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidenmenuMouseExited(evt);
            }
        });
        hidenmenu.add(buttonhidenmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        menuIcon.add(hidenmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 50));

        setting.setBackground(new java.awt.Color(255, 102, 51));
        setting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonsetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonsetting.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\—Pngtree—settings icon_4479688 (1).png")); // NOI18N
        buttonsetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonsettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonsettingMouseExited(evt);
            }
        });
        setting.add(buttonsetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        menuIcon.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 50, 50));

        linesetting.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout linesettingLayout = new javax.swing.GroupLayout(linesetting);
        linesetting.setLayout(linesettingLayout);
        linesettingLayout.setHorizontalGroup(
            linesettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linesettingLayout.setVerticalGroup(
            linesettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon.add(linesetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, -1));

        linechat.setBackground(new java.awt.Color(255, 102, 51));
        linechat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linechatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linechatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout linechatLayout = new javax.swing.GroupLayout(linechat);
        linechat.setLayout(linechatLayout);
        linechatLayout.setHorizontalGroup(
            linechatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linechatLayout.setVerticalGroup(
            linechatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon.add(linechat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 50, 10));

        buttonhidenmenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidenmenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\chat-icon.png")); // NOI18N
        buttonhidenmenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidenmenu2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidenmenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidenmenu2MouseExited(evt);
            }
        });
        menuIcon.add(buttonhidenmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 50, 50));

        menu.add(menuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 580));

        menuhide.setBackground(new java.awt.Color(51, 51, 51));
        menuhide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contact.setBackground(new java.awt.Color(51, 51, 51));
        contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setText("Contact");
        contact.setOpaque(true);
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactMouseExited(evt);
            }
        });
        menuhide.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 50));

        gomenu.setBackground(new java.awt.Color(51, 51, 51));
        gomenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gomenu.setForeground(new java.awt.Color(255, 255, 255));
        gomenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gomenu.setText("Menu");
        gomenu.setOpaque(true);
        gomenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gomenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gomenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gomenuMouseExited(evt);
            }
        });
        menuhide.add(gomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 50));

        homepage.setBackground(new java.awt.Color(51, 51, 51));
        homepage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homepage.setForeground(new java.awt.Color(255, 255, 255));
        homepage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homepage.setText("Home Page");
        homepage.setOpaque(true);
        homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homepageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homepageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homepageMouseExited(evt);
            }
        });
        menuhide.add(homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        cart.setBackground(new java.awt.Color(51, 51, 51));
        cart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cart.setForeground(new java.awt.Color(255, 255, 255));
        cart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cart.setText("Cart");
        cart.setOpaque(true);
        cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cartMouseExited(evt);
            }
        });
        menuhide.add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 50));

        favor.setBackground(new java.awt.Color(51, 51, 51));
        favor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        favor.setForeground(new java.awt.Color(255, 255, 255));
        favor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        favor.setText("Favorite");
        favor.setOpaque(true);
        favor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                favorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                favorMouseExited(evt);
            }
        });
        menuhide.add(favor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 50));

        menu.add(menuhide, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 580));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        sett.setPreferredSize(new java.awt.Dimension(50, 580));
        sett.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuIcon1.setBackground(new java.awt.Color(255, 102, 51));
        menuIcon1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehidenmenu1.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout linehidenmenu1Layout = new javax.swing.GroupLayout(linehidenmenu1);
        linehidenmenu1.setLayout(linehidenmenu1Layout);
        linehidenmenu1Layout.setHorizontalGroup(
            linehidenmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehidenmenu1Layout.setVerticalGroup(
            linehidenmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon1.add(linehidenmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 10));

        hidenmenu1.setBackground(new java.awt.Color(255, 102, 51));
        hidenmenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonhidenmenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidenmenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\PinClipart.com_cempasuchil-clipart_1812493.png")); // NOI18N
        buttonhidenmenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidenmenu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidenmenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidenmenu1MouseExited(evt);
            }
        });
        hidenmenu1.add(buttonhidenmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        menuIcon1.add(hidenmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 50));

        setting1.setBackground(new java.awt.Color(255, 102, 51));
        setting1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonsetting1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonsetting1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\—Pngtree—settings icon_4479688 (1).png")); // NOI18N
        buttonsetting1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsetting1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonsetting1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonsetting1MouseExited(evt);
            }
        });
        setting1.add(buttonsetting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        menuIcon1.add(setting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 50, 50));

        linesetting1.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout linesetting1Layout = new javax.swing.GroupLayout(linesetting1);
        linesetting1.setLayout(linesetting1Layout);
        linesetting1Layout.setHorizontalGroup(
            linesetting1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linesetting1Layout.setVerticalGroup(
            linesetting1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon1.add(linesetting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, -1));

        sett.add(menuIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 580));

        menuhide1.setBackground(new java.awt.Color(51, 51, 51));
        menuhide1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(51, 51, 51));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Log out");
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        menuhide1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 50));

        account.setBackground(new java.awt.Color(51, 51, 51));
        account.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        account.setForeground(new java.awt.Color(255, 255, 255));
        account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account.setText("Change password");
        account.setOpaque(true);
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountMouseExited(evt);
            }
        });
        menuhide1.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        sett.add(menuhide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 580));

        getContentPane().add(sett, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        header2.setBackground(new java.awt.Color(255, 102, 51));
        header2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\[CITYPNG.COM]HD Spoon & Fork Restaurant Cuisine White Icon PNG - 800x800.png")); // NOI18N
        jLabel1.setText("GLFOOD");
        header2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 270, 50));

        getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 710, 50));

        listfood.setBackground(new java.awt.Color(255, 255, 255));
        listfood.setPreferredSize(new java.awt.Dimension(710, 800));
        listfood.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product.setPreferredSize(new java.awt.Dimension(685, 800));
        product.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        food9.setBackground(new java.awt.Color(255, 255, 255));
        food9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodpic9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\picfood7.png")); // NOI18N
        foodpic9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodpic9MouseClicked(evt);
            }
        });
        food9.add(foodpic9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 160));

        namefood9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namefood9.setForeground(new java.awt.Color(255, 102, 51));
        namefood9.setText("Refreshing shrimp salad");
        food9.add(namefood9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        heart8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png")); // NOI18N
        heart8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heart8MouseClicked(evt);
            }
        });
        food9.add(heart8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        cost8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cost8.setForeground(new java.awt.Color(204, 0, 51));
        cost8.setText("150.000");
        food9.add(cost8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 20));

        product.add(food9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 200, 240));

        food8.setBackground(new java.awt.Color(255, 255, 255));
        food8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodpic8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\picfood8.png")); // NOI18N
        foodpic8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodpic8MouseClicked(evt);
            }
        });
        food8.add(foodpic8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 160));

        namefood8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namefood8.setForeground(new java.awt.Color(255, 102, 51));
        namefood8.setText("Grilled Salmon with Honey");
        food8.add(namefood8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        heart7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png")); // NOI18N
        heart7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heart7MouseClicked(evt);
            }
        });
        food8.add(heart7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        cost7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cost7.setForeground(new java.awt.Color(204, 0, 51));
        cost7.setText("250.000");
        food8.add(cost7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 20));

        product.add(food8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 200, 240));

        food7.setBackground(new java.awt.Color(255, 255, 255));
        food7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodpic7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\picfood9.png")); // NOI18N
        foodpic7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodpic7MouseClicked(evt);
            }
        });
        food7.add(foodpic7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 160));

        namefood7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namefood7.setForeground(new java.awt.Color(255, 102, 51));
        namefood7.setText("Crispy fruit sandwich");
        food7.add(namefood7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        heart6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png")); // NOI18N
        heart6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heart6MouseClicked(evt);
            }
        });
        food7.add(heart6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        cost6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cost6.setForeground(new java.awt.Color(204, 0, 51));
        cost6.setText("100.000");
        food7.add(cost6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 20));

        product.add(food7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 200, 240));

        food6.setBackground(new java.awt.Color(255, 255, 255));
        food6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodpic6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\picfood6.png")); // NOI18N
        foodpic6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodpic6MouseClicked(evt);
            }
        });
        food6.add(foodpic6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 160));

        namefood6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namefood6.setForeground(new java.awt.Color(255, 102, 51));
        namefood6.setText("Steak");
        food6.add(namefood6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        heart5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png")); // NOI18N
        heart5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heart5MouseClicked(evt);
            }
        });
        food6.add(heart5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        cost5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cost5.setForeground(new java.awt.Color(204, 0, 51));
        cost5.setText("150.000");
        food6.add(cost5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 20));

        product.add(food6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 200, 240));

        food5.setBackground(new java.awt.Color(255, 255, 255));
        food5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodpic5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\picfood5.png")); // NOI18N
        foodpic5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodpic5MouseClicked(evt);
            }
        });
        food5.add(foodpic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 160));

        namefood5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namefood5.setForeground(new java.awt.Color(255, 102, 51));
        namefood5.setText("Stir-fried crab with soy sauce");
        food5.add(namefood5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        heart4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png")); // NOI18N
        heart4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heart4MouseClicked(evt);
            }
        });
        food5.add(heart4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        cost4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cost4.setForeground(new java.awt.Color(204, 0, 51));
        cost4.setText("550.000");
        food5.add(cost4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 20));

        product.add(food5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 200, 240));

        food4.setBackground(new java.awt.Color(255, 255, 255));
        food4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodpic4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\picfood4.png")); // NOI18N
        foodpic4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodpic4MouseClicked(evt);
            }
        });
        food4.add(foodpic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 160));

        namefood4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namefood4.setForeground(new java.awt.Color(255, 102, 51));
        namefood4.setText("Deep fried peeled crab");
        food4.add(namefood4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        heart3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png")); // NOI18N
        heart3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heart3MouseClicked(evt);
            }
        });
        food4.add(heart3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        cost3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cost3.setForeground(new java.awt.Color(204, 0, 51));
        cost3.setText("350.000");
        food4.add(cost3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 20));

        product.add(food4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 200, 240));

        food3.setBackground(new java.awt.Color(255, 255, 255));
        food3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodpic3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\picfood3.png")); // NOI18N
        foodpic3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodpic3MouseClicked(evt);
            }
        });
        food3.add(foodpic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 160));

        namefood3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namefood3.setForeground(new java.awt.Color(255, 102, 51));
        namefood3.setText("Crispy fruit sandwich");
        food3.add(namefood3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        heart2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png")); // NOI18N
        heart2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heart2MouseClicked(evt);
            }
        });
        food3.add(heart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        cost2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cost2.setForeground(new java.awt.Color(204, 0, 51));
        cost2.setText("100.000");
        food3.add(cost2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 20));

        product.add(food3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 200, 240));

        food2.setBackground(new java.awt.Color(255, 255, 255));
        food2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodpic2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\picfood2.png")); // NOI18N
        foodpic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodpic2MouseClicked(evt);
            }
        });
        food2.add(foodpic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 160));

        namefood2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namefood2.setForeground(new java.awt.Color(255, 102, 51));
        namefood2.setText("Grilled pork ribs with pepper");
        food2.add(namefood2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        heart1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png")); // NOI18N
        heart1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heart1MouseClicked(evt);
            }
        });
        food2.add(heart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        cost1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cost1.setForeground(new java.awt.Color(204, 0, 51));
        cost1.setText("250.000");
        food2.add(cost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 20));

        product.add(food2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 200, 240));

        food1.setBackground(new java.awt.Color(255, 255, 255));
        food1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodpic1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\picfood1.png")); // NOI18N
        foodpic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodpic1MouseClicked(evt);
            }
        });
        food1.add(foodpic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 160));

        namefood1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namefood1.setForeground(new java.awt.Color(255, 102, 51));
        namefood1.setText("Deep fried shrimp with salted");
        food1.add(namefood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        foodname2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        foodname2.setForeground(new java.awt.Color(255, 102, 51));
        foodname2.setText("egg sauce");
        food1.add(foodname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 20));

        heart.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png")); // NOI18N
        heart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heartMouseClicked(evt);
            }
        });
        food1.add(heart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        cost.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cost.setForeground(new java.awt.Color(204, 0, 51));
        cost.setText("150.000");
        food1.add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 60, 20));

        product.add(food1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 240));

        listproduct.setViewportView(product);

        listfood.add(listproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 270));

        getContentPane().add(listfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 710, 330));

        header3.setBackground(new java.awt.Color(255, 153, 51));
        header3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Delicious food every day");
        header3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 250, 30));

        getContentPane().add(header3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 710, 50));

        graphics.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setForeground(new java.awt.Color(60, 63, 65));
        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\back.png")); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        graphics.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 50, 50));

        next.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\next.png")); // NOI18N
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextMouseExited(evt);
            }
        });
        graphics.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 50, 50));

        picgrap1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\food6.jpeg")); // NOI18N
        graphics.add(picgrap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 210));

        getContentPane().add(graphics, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 710, 210));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Thiết kế chưa có tên.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 580));

        dashboardview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Thiết kế chưa có tên.png")); // NOI18N
        dashboardview.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 0, 760, 580));

        getContentPane().add(dashboardview, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 510, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    public void changecolorLable(JLabel label, Color rand) {
        label.setBackground(rand);
    }

    public void clickmenu(JPanel h1, JPanel h2, int numberbool) {
        if (numberbool == 1) {
            h1.setBackground(new Color(51, 51, 51));
            h2.setBackground(new Color(255, 102, 51));
        } else {
            h1.setBackground(new Color(255, 102, 51));
            h2.setBackground(new Color(51, 51, 51));
        }
    }

    public void changeimage(JLabel button, String resourcheimg) {
        button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button.setIcon(new javax.swing.ImageIcon(resourcheimg));
    }

    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button) {
        if (dashboard == true) {
            menushowhide.setPreferredSize(new Dimension(250, menushowhide.getHeight()));
            changeimage(button, "C:\\Users\\ACER\\Downloads\\white-down-arrow-png-2-300x300.png");
        } else {
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(button, "C:\\Users\\ACER\\Downloads\\PinClipart.com_cempasuchil-clipart_1812493.png");
            changecolor(hidenmenu, new Color(255, 102, 51));
        }
    }

    public void hideshowsetting(JPanel menushowhide, boolean dashboard, JLabel button) {
        if (dashboard == true) {
            menushowhide.setPreferredSize(new Dimension(250, menushowhide.getHeight()));
            changeimage(button, "C:\\Users\\ACER\\Downloads\\white-down-arrow-png-2-300x300.png");
        } else {
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(button, "C:\\Users\\ACER\\Downloads\\—Pngtree—settings icon_4479688 (1).png");
            changecolor(setting, new Color(255, 102, 51));
        }
    }
    private void buttonhidenmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenuMouseEntered
        changecolor(linehidenmenu, Color.red);
    }//GEN-LAST:event_buttonhidenmenuMouseEntered

    private void buttonhidenmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenuMouseExited
        changecolor(linehidenmenu, new Color(255, 102, 51));
    }//GEN-LAST:event_buttonhidenmenuMouseExited

    private void buttonhidenmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenuMouseClicked
        clickmenu(hidenmenu, setting, 1);
        if (a == true) {
            hideshow(menu, a, buttonhidenmenu);
            SwingUtilities.updateComponentTreeUI(this);
            a = false;

            sett.setPreferredSize(new Dimension(50, sett.getHeight()));
            changeimage(buttonsetting, "C:\\Users\\ACER\\Downloads\\—Pngtree—settings icon_4479688 (1).png");
            changecolor(setting, new Color(255, 102, 51));
            SwingUtilities.updateComponentTreeUI(this);
        } else {
            hideshow(menu, a, buttonhidenmenu);
            SwingUtilities.updateComponentTreeUI(this);
            a = true;
        }

    }//GEN-LAST:event_buttonhidenmenuMouseClicked

    private void buttonsettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsettingMouseClicked
        clickmenu(setting, hidenmenu, 1);
        if (b == true) {
            hideshowsetting(sett, b, buttonsetting);
            SwingUtilities.updateComponentTreeUI(this);
            b = false;

            menu.setPreferredSize(new Dimension(50, menu.getHeight()));
            changeimage(buttonhidenmenu, "C:\\Users\\ACER\\Downloads\\PinClipart.com_cempasuchil-clipart_1812493.png");
            changecolor(hidenmenu, new Color(255, 102, 51));

        } else {
            hideshowsetting(sett, b, buttonsetting);
            SwingUtilities.updateComponentTreeUI(this);
            b = true;
        }
    }//GEN-LAST:event_buttonsettingMouseClicked

    private void buttonsettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsettingMouseEntered
        changecolor(linesetting, Color.red);
    }//GEN-LAST:event_buttonsettingMouseEntered

    private void buttonsettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsettingMouseExited
        changecolor(linesetting, new Color(255, 102, 51));
    }//GEN-LAST:event_buttonsettingMouseExited

    private void buttonhidenmenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonhidenmenu1MouseClicked

    private void buttonhidenmenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonhidenmenu1MouseEntered

    private void buttonhidenmenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonhidenmenu1MouseExited

    private void buttonsetting1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsetting1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonsetting1MouseClicked

    private void buttonsetting1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsetting1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonsetting1MouseEntered

    private void buttonsetting1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsetting1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonsetting1MouseExited

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        if (evt.getClickCount() == 1) {
            changeimage(picgrap1, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\food6.jpeg");
        } else {
            changeimage(picgrap1, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\food8.jpg");
        }
    }//GEN-LAST:event_nextMouseClicked

    private void nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseEntered
        changeimage(next, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\nextblack.png");
    }//GEN-LAST:event_nextMouseEntered

    private void nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseExited
        changeimage(next, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\next.png");
    }//GEN-LAST:event_nextMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        if (evt.getClickCount() == 1) {
            changeimage(picgrap1, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\food7.jpg");
        } else {
            changeimage(picgrap1, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\food5.jpg");
        }
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        changeimage(back, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\backblack.png");

        menu.setPreferredSize(new Dimension(50, menu.getHeight()));
        changeimage(buttonhidenmenu, "C:\\Users\\ACER\\Downloads\\PinClipart.com_cempasuchil-clipart_1812493.png");
        changecolor(hidenmenu, new Color(255, 102, 51));

        sett.setPreferredSize(new Dimension(50, sett.getHeight()));
        changeimage(buttonsetting, "C:\\Users\\ACER\\Downloads\\—Pngtree—settings icon_4479688 (1).png");
        changecolor(setting, new Color(255, 102, 51));
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        changeimage(back, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\back.png");
    }//GEN-LAST:event_backMouseExited

    private void heartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heartMouseClicked

        if (evt.getClickCount() == 1) {
            changeimage(heart, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            add();
        } else {
            changeimage(heart, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png");
            delete();
        }


    }//GEN-LAST:event_heartMouseClicked

    private void heart1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heart1MouseClicked
        if (evt.getClickCount() == 1) {
            changeimage(heart1, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            add1();
        } else {
            changeimage(heart1, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png");
            delete1();
        }

    }//GEN-LAST:event_heart1MouseClicked

    private void heart2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heart2MouseClicked
        if (evt.getClickCount() == 1) {
            changeimage(heart2, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            add2();
        } else {
            changeimage(heart2, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png");
            delete2();
        }

    }//GEN-LAST:event_heart2MouseClicked

    private void heart3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heart3MouseClicked
        if (evt.getClickCount() == 1) {
            changeimage(heart3, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            add3();
        } else {
            changeimage(heart3, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png");
            delete3();
        }

    }//GEN-LAST:event_heart3MouseClicked

    private void heart4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heart4MouseClicked
        if (evt.getClickCount() == 1) {
            changeimage(heart4, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            add4();
        } else {
            changeimage(heart4, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png");
            delete4();
        }

    }//GEN-LAST:event_heart4MouseClicked

    private void heart5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heart5MouseClicked
        if (evt.getClickCount() == 1) {
            changeimage(heart5, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            add5();
        } else {
            changeimage(heart5, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png");
            delete5();
        }

    }//GEN-LAST:event_heart5MouseClicked

    private void heart6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heart6MouseClicked
        if (evt.getClickCount() == 1) {
            changeimage(heart6, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            add6();
        } else {
            changeimage(heart6, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png");
            delete6();
        }

    }//GEN-LAST:event_heart6MouseClicked

    private void heart7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heart7MouseClicked
        if (evt.getClickCount() == 1) {
            changeimage(heart7, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            add7();
        } else {
            changeimage(heart7, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png");
            delete7();
        }

    }//GEN-LAST:event_heart7MouseClicked

    private void heart8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heart8MouseClicked
        if (evt.getClickCount() == 1) {
            changeimage(heart8, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            add8();
        } else {
            changeimage(heart8, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\heart.png");
            delete8();
        }

    }//GEN-LAST:event_heart8MouseClicked

    private void homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseClicked
        dispose();
        FoodHomePage food = new FoodHomePage();
        food.setVisible(true);
        food.setLocationRelativeTo(null);
    }//GEN-LAST:event_homepageMouseClicked

    private void homepageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseEntered
        changecolorLable(homepage, new Color(204, 0, 51));
    }//GEN-LAST:event_homepageMouseEntered

    private void homepageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseExited
        changecolorLable(homepage, new Color(51, 51, 51));
    }//GEN-LAST:event_homepageMouseExited

    private void gomenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gomenuMouseClicked
        dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_gomenuMouseClicked

    private void gomenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gomenuMouseEntered
        changecolorLable(gomenu, new Color(204, 0, 51));
    }//GEN-LAST:event_gomenuMouseEntered

    private void gomenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gomenuMouseExited
        changecolorLable(gomenu, new Color(51, 51, 51));
    }//GEN-LAST:event_gomenuMouseExited

    private void foodpic1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodpic1MouseClicked
        dispose();
        Sell10 s10 = new Sell10();
        s10.setVisible(true);
        s10.setLocationRelativeTo(null);
    }//GEN-LAST:event_foodpic1MouseClicked

    private void foodpic2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodpic2MouseClicked
        dispose();
        Sell11 s11 = new Sell11();
        s11.setVisible(true);
        s11.setLocationRelativeTo(null);
    }//GEN-LAST:event_foodpic2MouseClicked

    private void foodpic3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodpic3MouseClicked
        dispose();
        Sell12 s12 = new Sell12();
        s12.setVisible(true);
        s12.setLocationRelativeTo(null);
    }//GEN-LAST:event_foodpic3MouseClicked

    private void foodpic4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodpic4MouseClicked
        dispose();
        Sell13 s13 = new Sell13();
        s13.setVisible(true);
        s13.setLocationRelativeTo(null);
    }//GEN-LAST:event_foodpic4MouseClicked

    private void foodpic5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodpic5MouseClicked
        dispose();
        Sell14 s14 = new Sell14();
        s14.setVisible(true);
        s14.setLocationRelativeTo(null);
    }//GEN-LAST:event_foodpic5MouseClicked

    private void foodpic6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodpic6MouseClicked
        dispose();
        Sell15 s15 = new Sell15();
        s15.setVisible(true);
        s15.setLocationRelativeTo(null);
    }//GEN-LAST:event_foodpic6MouseClicked

    private void foodpic9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodpic9MouseClicked
        dispose();
        Sell16 s16 = new Sell16();
        s16.setVisible(true);
        s16.setLocationRelativeTo(null);
    }//GEN-LAST:event_foodpic9MouseClicked

    private void foodpic8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodpic8MouseClicked
        dispose();
        Sell17 s17 = new Sell17();
        s17.setVisible(true);
        s17.setLocationRelativeTo(null);
    }//GEN-LAST:event_foodpic8MouseClicked

    private void foodpic7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodpic7MouseClicked
        dispose();
        Sell18 s18 = new Sell18();
        s18.setVisible(true);
        s18.setLocationRelativeTo(null);
    }//GEN-LAST:event_foodpic7MouseClicked

    private void cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseClicked
        dispose();
        cart cart = new cart();
        cart.setVisible(true);
        cart.setLocationRelativeTo(null);
    }//GEN-LAST:event_cartMouseClicked

    private void cartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseEntered
        changecolorLable(cart, new Color(204, 0, 51));

    }//GEN-LAST:event_cartMouseEntered

    private void cartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseExited
        changecolorLable(cart, new Color(51, 51, 51));
    }//GEN-LAST:event_cartMouseExited

    private void contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseClicked
        dispose();
        contact con = new contact();
        con.setVisible(true);
        con.setLocationRelativeTo(null);
    }//GEN-LAST:event_contactMouseClicked

    private void contactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseEntered
        changecolorLable(contact, new Color(204, 0, 51));
    }//GEN-LAST:event_contactMouseEntered

    private void contactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseExited
        changecolorLable(contact, new Color(51, 51, 51));
    }//GEN-LAST:event_contactMouseExited

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        dispose();
        changepassword change = new changepassword();
        change.setVisible(true);
    }//GEN-LAST:event_accountMouseClicked

    private void accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseEntered
        changecolorLable(account, new Color(204, 0, 51));
    }//GEN-LAST:event_accountMouseEntered

    private void accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseExited
        changecolorLable(account, new Color(51, 51, 51));
    }//GEN-LAST:event_accountMouseExited

    private void buttonhidenmenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu2MouseClicked
        ChatCustomClient chatclient = new ChatCustomClient();
        chatclient.setVisible(true);

    }//GEN-LAST:event_buttonhidenmenu2MouseClicked

    private void buttonhidenmenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu2MouseEntered
        changecolor(linechat, Color.red);
        changeimage(buttonhidenmenu2, "C:\\Users\\ACER\\Downloads\\chat-icon (1).png");
    }//GEN-LAST:event_buttonhidenmenu2MouseEntered

    private void buttonhidenmenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu2MouseExited
        changecolor(linechat, new Color(255, 102, 51));
        changeimage(buttonhidenmenu2, "C:\\Users\\ACER\\Downloads\\chat-icon.png");
    }//GEN-LAST:event_buttonhidenmenu2MouseExited

    private void linechatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linechatMouseEntered

    }//GEN-LAST:event_linechatMouseEntered

    private void linechatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linechatMouseExited

    }//GEN-LAST:event_linechatMouseExited

    private void favorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favorMouseClicked
        dispose();
        Favorite f = new Favorite();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_favorMouseClicked

    private void favorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favorMouseEntered
        changecolorLable(favor, new Color(204, 0, 51));

    }//GEN-LAST:event_favorMouseEntered

    private void favorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favorMouseExited

        changecolorLable(favor, new Color(51, 51, 51));
    }//GEN-LAST:event_favorMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        dispose();
        InforInter infor = new InforInter();
        infor.setVisible(true);
        infor.setLocationRelativeTo(null);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        changecolorLable(logout, new Color(204, 0, 51));

    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited

        changecolorLable(logout, new Color(51, 51, 51));
    }//GEN-LAST:event_logoutMouseExited
    public void add() {
        try {

            String sql = "Insert into Favorite (FoodName, Cost) values ('"
                    + namefood1.getText() + "','" + cost.getText() + "')";

            int record = executeDB(sql);

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void add1() {
        try {

            String sql = "Insert into Favorite (FoodName, Cost) values ('"
                    + namefood2.getText() + "','" + cost1.getText() + "')";

            int record = executeDB(sql);

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void add2() {
        try {

            String sql = "Insert into Favorite (FoodName, Cost) values ('"
                    + namefood3.getText() + "','" + cost2.getText() + "')";

            int record = executeDB(sql);

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void add3() {
        try {

            String sql = "Insert into Favorite (FoodName, Cost) values ('"
                    + namefood4.getText() + "','" + cost3.getText() + "')";

            int record = executeDB(sql);

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void add4() {
        try {

            String sql = "Insert into Favorite (FoodName, Cost) values ('"
                    + namefood5.getText() + "','" + cost4.getText() + "')";

            int record = executeDB(sql);

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void add5() {
        try {

            String sql = "Insert into Favorite (FoodName, Cost) values ('"
                    + namefood6.getText() + "','" + cost5.getText() + "')";

            int record = executeDB(sql);

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void add6() {
        try {

            String sql = "Insert into Favorite (FoodName, Cost) values ('"
                    + namefood7.getText() + "','" + cost6.getText() + "')";

            int record = executeDB(sql);

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void add7() {
        try {

            String sql = "Insert into Favorite (FoodName, Cost) values ('"
                    + namefood8.getText() + "','" + cost7.getText() + "')";

            int record = executeDB(sql);

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void add8() {
        try {

            String sql = "Insert into Favorite (FoodName, Cost) values ('"
                    + namefood9.getText() + "','" + cost8.getText() + "')";

            int record = executeDB(sql);

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public static void connect() {
        try {
            String sqlServer = "jdbc:sqlserver://LAPTOP-EUQVAG1I\\SQLEXPRESS;databasename=GLFood;user=sa;password=123456789";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection(sqlServer);
            Statement stm = conn.createStatement();
        } catch (Exception e) {
            // TODO: handle exception
        }

    }

    public int executeDB(String sql) {
        int record = 0;// number of records have been changed in db
        try {
            connect();
            Statement stmt = conn.createStatement();
            record = stmt.executeUpdate(sql);
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
        }
        return record;
    }

    public void delete() {
        try {

            int record = executeDB(
                    "Delete from Favorite where FoodName ='" + namefood1.getText() + "'");

        } catch (Exception e2) {
            // TODO: handle exception
        }

    }

    public void delete1() {
        try {

            int record = executeDB(
                    "Delete from Favorite where FoodName ='" + namefood2.getText() + "'");

        } catch (Exception e2) {
            // TODO: handle exception
        }

    }

    public void delete2() {
        try {

            int record = executeDB(
                    "Delete from Favorite where FoodName ='" + namefood3.getText() + "'");

        } catch (Exception e2) {
            // TODO: handle exception
        }

    }

    public void delete3() {
        try {

            int record = executeDB(
                    "Delete from Favorite where FoodName ='" + namefood4.getText() + "'");

        } catch (Exception e2) {
            // TODO: handle exception
        }

    }

    public void delete4() {
        try {

            int record = executeDB(
                    "Delete from Favorite where FoodName ='" + namefood5.getText() + "'");

        } catch (Exception e2) {
            // TODO: handle exception
        }

    }

    public void delete5() {
        try {

            int record = executeDB(
                    "Delete from Favorite where FoodName ='" + namefood6.getText() + "'");

        } catch (Exception e2) {
            // TODO: handle exception
        }

    }

    public void delete6() {
        try {

            int record = executeDB(
                    "Delete from Favorite where FoodName ='" + namefood7.getText() + "'");

        } catch (Exception e2) {
            // TODO: handle exception
        }

    }

    public void delete7() {
        try {

            int record = executeDB(
                    "Delete from Favorite where FoodName ='" + namefood8.getText() + "'");

        } catch (Exception e2) {
            // TODO: handle exception
        }

    }

    public void delete8() {
        try {

            int record = executeDB(
                    "Delete from Favorite where FoodName ='" + namefood9.getText() + "'");

        } catch (Exception e2) {
            // TODO: handle exception
        }

    }

    public void heart1() {
        try {
            connect();

            String sql = "select * from Favorite where FoodName = '" + namefood1.getText() + "'";

            prs = conn.prepareStatement(sql);
            rs = prs.executeQuery();
            if (rs.next()) {

                changeimage(heart, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            }

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void heart2() {
        try {
            connect();

            String sql = "select * from Favorite where FoodName = '" + namefood2.getText() + "'";

            prs = conn.prepareStatement(sql);
            rs = prs.executeQuery();
            if (rs.next()) {
                changeimage(heart1, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            } 

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void heart3() {
        try {
            connect();

            String sql = "select * from Favorite where FoodName = '" + namefood3.getText() + "'";

            prs = conn.prepareStatement(sql);
            rs = prs.executeQuery();
            if (rs.next()) {
                changeimage(heart2, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            } 

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void heart4() {
        try {
            connect();

            String sql = "select * from Favorite where FoodName = '" + namefood4.getText() + "'";

            prs = conn.prepareStatement(sql);
            rs = prs.executeQuery();
            if (rs.next()) {
                changeimage(heart3, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            } 

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void heart5() {
        try {
            connect();

            String sql = "select * from Favorite where FoodName = '" + namefood5.getText() + "'";

            prs = conn.prepareStatement(sql);
            rs = prs.executeQuery();
            if (rs.next()) {
                changeimage(heart4, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            } 
        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void heart6() {
        try {
            connect();

            String sql = "select * from Favorite where FoodName = '" + namefood6.getText() + "'";

            prs = conn.prepareStatement(sql);
            rs = prs.executeQuery();
            if (rs.next()) {
                changeimage(heart5, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            } 

        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void heart7() {
        try {
            connect();

            String sql = "select * from Favorite where FoodName = '" + namefood7.getText() + "'";

            prs = conn.prepareStatement(sql);
            rs = prs.executeQuery();
            if (rs.next()) {
                changeimage(heart6, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            } 
        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void heart8() {
        try {
            connect();

            String sql = "select * from Favorite where FoodName = '" + namefood8.getText() + "'";

            prs = conn.prepareStatement(sql);
            rs = prs.executeQuery();
            if (rs.next()) {
                changeimage(heart7, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            } 
        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    public void heart9() {
        try {
            connect();

            String sql = "select * from Favorite where FoodName = '" + namefood9.getText() + "'";

            prs = conn.prepareStatement(sql);
            rs = prs.executeQuery();
            if (rs.next()) {
                changeimage(heart8, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Heart-icon.png");
            } 
        } catch (Exception e2) {
            // TODO: handle exception
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FoodHomePage food = new FoodHomePage();
                food.setVisible(true);
                food.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel buttonhidenmenu;
    private javax.swing.JLabel buttonhidenmenu1;
    private javax.swing.JLabel buttonhidenmenu2;
    private javax.swing.JLabel buttonsetting;
    private javax.swing.JLabel buttonsetting1;
    private javax.swing.JLabel cart;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel cost;
    private javax.swing.JLabel cost1;
    private javax.swing.JLabel cost2;
    private javax.swing.JLabel cost3;
    private javax.swing.JLabel cost4;
    private javax.swing.JLabel cost5;
    private javax.swing.JLabel cost6;
    private javax.swing.JLabel cost7;
    private javax.swing.JLabel cost8;
    private javax.swing.JPanel dashboardview;
    private javax.swing.JLabel favor;
    private javax.swing.JPanel food1;
    private javax.swing.JPanel food2;
    private javax.swing.JPanel food3;
    private javax.swing.JPanel food4;
    private javax.swing.JPanel food5;
    private javax.swing.JPanel food6;
    private javax.swing.JPanel food7;
    private javax.swing.JPanel food8;
    private javax.swing.JPanel food9;
    private javax.swing.JLabel foodname2;
    private javax.swing.JLabel foodpic1;
    private javax.swing.JLabel foodpic2;
    private javax.swing.JLabel foodpic3;
    private javax.swing.JLabel foodpic4;
    private javax.swing.JLabel foodpic5;
    private javax.swing.JLabel foodpic6;
    private javax.swing.JLabel foodpic7;
    private javax.swing.JLabel foodpic8;
    private javax.swing.JLabel foodpic9;
    private javax.swing.JLabel gomenu;
    private javax.swing.JPanel graphics;
    private javax.swing.JPanel header2;
    private javax.swing.JPanel header3;
    private javax.swing.JLabel heart;
    private javax.swing.JLabel heart1;
    private javax.swing.JLabel heart2;
    private javax.swing.JLabel heart3;
    private javax.swing.JLabel heart4;
    private javax.swing.JLabel heart5;
    private javax.swing.JLabel heart6;
    private javax.swing.JLabel heart7;
    private javax.swing.JLabel heart8;
    private javax.swing.JPanel hidenmenu;
    private javax.swing.JPanel hidenmenu1;
    private javax.swing.JLabel homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel linechat;
    private javax.swing.JPanel linehidenmenu;
    private javax.swing.JPanel linehidenmenu1;
    private javax.swing.JPanel linesetting;
    private javax.swing.JPanel linesetting1;
    private javax.swing.JPanel listfood;
    private javax.swing.JScrollPane listproduct;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JPanel menuIcon1;
    private javax.swing.JPanel menuhide;
    private javax.swing.JPanel menuhide1;
    private javax.swing.JLabel namefood1;
    private javax.swing.JLabel namefood2;
    private javax.swing.JLabel namefood3;
    private javax.swing.JLabel namefood4;
    private javax.swing.JLabel namefood5;
    private javax.swing.JLabel namefood6;
    private javax.swing.JLabel namefood7;
    private javax.swing.JLabel namefood8;
    private javax.swing.JLabel namefood9;
    private javax.swing.JLabel next;
    private javax.swing.JLabel picgrap1;
    private javax.swing.JPanel product;
    private javax.swing.JPanel sett;
    private javax.swing.JPanel setting;
    private javax.swing.JPanel setting1;
    // End of variables declaration//GEN-END:variables
}
