/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package glfood;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.List;
import java.sql.DriverManager;
import java.text.Normalizer;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    static Connection conn;
    static PreparedStatement prs;
    static ResultSet rs;

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfuser1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        buttonLogin = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfuser1.setBackground(new java.awt.Color(255, 255, 255));
        tfuser1.setText("Enter your username");
        tfuser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuser1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 270, 40));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 270, 40));

        back.setBackground(new java.awt.Color(255, 51, 51));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, 30));

        buttonLogin.setBackground(new java.awt.Color(255, 153, 0));
        buttonLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Log in");
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoginMouseClicked(evt);
            }
        });
        getContentPane().add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 230, 40));
        buttonLogin.getAccessibleContext().setAccessibleDescription("");

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\GLFOODLogin (1).png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfuser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuser1ActionPerformed

    private void buttonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseClicked
        if (getTfuser1().getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please input your user!");
        } else {
            if (jPasswordField1.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please input your password!");
            } else {
                if ((getTfuser1().getText().equals("admin"))&&(jPasswordField1.getText().equals("1234"))) {
                    dispose();
                    AdminHomePage a = new AdminHomePage();
                    a.setVisible(true);
                    a.setLocationRelativeTo(null);
                } else {

                    try {
                        String sqlServer = "jdbc:sqlserver://LAPTOP-EUQVAG1I\\SQLEXPRESS;databasename=GLFood;user=sa;password=123456789";
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                        Connection connection = DriverManager.getConnection(sqlServer);
                        String sql = "Select * from AccountGL where Username = ? and Password = ? ";
                        PreparedStatement ps = connection.prepareStatement(sql);
                        ps.setString(1, getTfuser1().getText());
                        ps.setString(2, jPasswordField1.getText());

                        ResultSet rs = ps.executeQuery();
                        if (rs.next()) {
                            dispose();
                            FoodHomePage f = new FoodHomePage();
                            f.setVisible(true);

                        } else {
                            JOptionPane.showMessageDialog(this, "Your login failed! No account or wrong password!");
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    }//GEN-LAST:event_buttonLoginMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        InforInter infor = new InforInter();
        infor.setVisible(true);

    }//GEN-LAST:event_backActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login login = new Login();
                login.setVisible(true);
                login.setLocationRelativeTo(null);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField tfuser1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tfuser1
     */
    public javax.swing.JTextField getTfuser1() {
        return tfuser1;
    }
}
