/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package glfood;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.sql.Statement;
import java.net.Socket;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ACER
 */
public class Sell15 extends javax.swing.JFrame {

    /**
     * Creates new form Sell
     */
    boolean a = true;
    boolean b = true;
    static Connection conn;
    static PreparedStatement prs;
    static ResultSet rs;
    ChatMessageSocket mSocket;
    private javax.swing.JTextPane display;

    public Sell15() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        linehidenmenu = new javax.swing.JPanel();
        hidenmenu = new javax.swing.JPanel();
        buttonhidenmenu = new javax.swing.JLabel();
        setting = new javax.swing.JPanel();
        buttonsetting = new javax.swing.JLabel();
        linesetting = new javax.swing.JPanel();
        linechat = new javax.swing.JPanel();
        buttonhidenmenu2 = new javax.swing.JLabel();
        menuhide = new javax.swing.JPanel();
        contact = new javax.swing.JLabel();
        gomenu = new javax.swing.JLabel();
        homepage = new javax.swing.JLabel();
        cart = new javax.swing.JLabel();
        favor = new javax.swing.JLabel();
        sett = new javax.swing.JPanel();
        menuIcon1 = new javax.swing.JPanel();
        linehidenmenu1 = new javax.swing.JPanel();
        hidenmenu1 = new javax.swing.JPanel();
        buttonhidenmenu1 = new javax.swing.JLabel();
        setting1 = new javax.swing.JPanel();
        buttonsetting1 = new javax.swing.JLabel();
        linesetting1 = new javax.swing.JPanel();
        menuhide1 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        header2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        headerMenu = new javax.swing.JPanel();
        Order = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        background2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        background3 = new javax.swing.JPanel();
        picfood1 = new javax.swing.JLabel();
        namefood1 = new javax.swing.JLabel();
        cost1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        number = new javax.swing.JLabel();
        addcart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setPreferredSize(new java.awt.Dimension(50, 580));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuIcon.setBackground(new java.awt.Color(255, 102, 51));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehidenmenu.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout linehidenmenuLayout = new javax.swing.GroupLayout(linehidenmenu);
        linehidenmenu.setLayout(linehidenmenuLayout);
        linehidenmenuLayout.setHorizontalGroup(
            linehidenmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehidenmenuLayout.setVerticalGroup(
            linehidenmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon.add(linehidenmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 10));

        hidenmenu.setBackground(new java.awt.Color(255, 102, 51));
        hidenmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonhidenmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidenmenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\PinClipart.com_cempasuchil-clipart_1812493.png")); // NOI18N
        buttonhidenmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidenmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidenmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidenmenuMouseExited(evt);
            }
        });
        hidenmenu.add(buttonhidenmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        menuIcon.add(hidenmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 50));

        setting.setBackground(new java.awt.Color(255, 102, 51));
        setting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonsetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonsetting.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\—Pngtree—settings icon_4479688 (1).png")); // NOI18N
        buttonsetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonsettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonsettingMouseExited(evt);
            }
        });
        setting.add(buttonsetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        menuIcon.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 50, 50));

        linesetting.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout linesettingLayout = new javax.swing.GroupLayout(linesetting);
        linesetting.setLayout(linesettingLayout);
        linesettingLayout.setHorizontalGroup(
            linesettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linesettingLayout.setVerticalGroup(
            linesettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon.add(linesetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, -1));

        linechat.setBackground(new java.awt.Color(255, 102, 51));
        linechat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linechatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linechatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout linechatLayout = new javax.swing.GroupLayout(linechat);
        linechat.setLayout(linechatLayout);
        linechatLayout.setHorizontalGroup(
            linechatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linechatLayout.setVerticalGroup(
            linechatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon.add(linechat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 50, 10));

        buttonhidenmenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidenmenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\chat-icon.png")); // NOI18N
        buttonhidenmenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidenmenu2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidenmenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidenmenu2MouseExited(evt);
            }
        });
        menuIcon.add(buttonhidenmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 50, 50));

        menu.add(menuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 580));

        menuhide.setBackground(new java.awt.Color(51, 51, 51));
        menuhide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contact.setBackground(new java.awt.Color(51, 51, 51));
        contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setText("Contact");
        contact.setOpaque(true);
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactMouseExited(evt);
            }
        });
        menuhide.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 50));

        gomenu.setBackground(new java.awt.Color(51, 51, 51));
        gomenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gomenu.setForeground(new java.awt.Color(255, 255, 255));
        gomenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gomenu.setText("Menu");
        gomenu.setOpaque(true);
        gomenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gomenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gomenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gomenuMouseExited(evt);
            }
        });
        menuhide.add(gomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 50));

        homepage.setBackground(new java.awt.Color(51, 51, 51));
        homepage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homepage.setForeground(new java.awt.Color(255, 255, 255));
        homepage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homepage.setText("Home Page");
        homepage.setOpaque(true);
        homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homepageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homepageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homepageMouseExited(evt);
            }
        });
        menuhide.add(homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        cart.setBackground(new java.awt.Color(51, 51, 51));
        cart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cart.setForeground(new java.awt.Color(255, 255, 255));
        cart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cart.setText("Cart");
        cart.setOpaque(true);
        cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cartMouseExited(evt);
            }
        });
        menuhide.add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 50));

        favor.setBackground(new java.awt.Color(51, 51, 51));
        favor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        favor.setForeground(new java.awt.Color(255, 255, 255));
        favor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        favor.setText("Favorite");
        favor.setOpaque(true);
        favor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                favorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                favorMouseExited(evt);
            }
        });
        menuhide.add(favor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 50));

        menu.add(menuhide, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 580));

        background.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        sett.setPreferredSize(new java.awt.Dimension(50, 580));
        sett.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuIcon1.setBackground(new java.awt.Color(255, 102, 51));
        menuIcon1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehidenmenu1.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout linehidenmenu1Layout = new javax.swing.GroupLayout(linehidenmenu1);
        linehidenmenu1.setLayout(linehidenmenu1Layout);
        linehidenmenu1Layout.setHorizontalGroup(
            linehidenmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehidenmenu1Layout.setVerticalGroup(
            linehidenmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon1.add(linehidenmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 10));

        hidenmenu1.setBackground(new java.awt.Color(255, 102, 51));
        hidenmenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonhidenmenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidenmenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\PinClipart.com_cempasuchil-clipart_1812493.png")); // NOI18N
        buttonhidenmenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidenmenu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidenmenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidenmenu1MouseExited(evt);
            }
        });
        hidenmenu1.add(buttonhidenmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        menuIcon1.add(hidenmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 50));

        setting1.setBackground(new java.awt.Color(255, 102, 51));
        setting1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonsetting1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonsetting1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\—Pngtree—settings icon_4479688 (1).png")); // NOI18N
        buttonsetting1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsetting1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonsetting1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonsetting1MouseExited(evt);
            }
        });
        setting1.add(buttonsetting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        menuIcon1.add(setting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 50, 50));

        linesetting1.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout linesetting1Layout = new javax.swing.GroupLayout(linesetting1);
        linesetting1.setLayout(linesetting1Layout);
        linesetting1Layout.setHorizontalGroup(
            linesetting1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linesetting1Layout.setVerticalGroup(
            linesetting1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon1.add(linesetting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, -1));

        sett.add(menuIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 580));

        menuhide1.setBackground(new java.awt.Color(51, 51, 51));
        menuhide1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(51, 51, 51));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Log out");
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        menuhide1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 50));

        account.setBackground(new java.awt.Color(51, 51, 51));
        account.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        account.setForeground(new java.awt.Color(255, 255, 255));
        account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account.setText("Change password");
        account.setOpaque(true);
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountMouseExited(evt);
            }
        });
        menuhide1.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        sett.add(menuhide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 580));

        background.add(sett, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        header2.setBackground(new java.awt.Color(255, 102, 51));
        header2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\[CITYPNG.COM]HD Spoon & Fork Restaurant Cuisine White Icon PNG - 800x800.png")); // NOI18N
        jLabel1.setText("GLFOOD");
        header2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 270, 50));

        background.add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 710, 50));

        headerMenu.setBackground(new java.awt.Color(255, 153, 51));
        headerMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Order.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Order.setForeground(new java.awt.Color(255, 255, 255));
        Order.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Order.setText("ORDER");
        headerMenu.add(Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 170, 30));

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\back.png")); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        headerMenu.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        background.add(headerMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 710, 50));

        background2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(60, 63, 65));
        jScrollPane1.setForeground(new java.awt.Color(60, 63, 65));

        background3.setBackground(new java.awt.Color(255, 255, 255));
        background3.setPreferredSize(new java.awt.Dimension(680, 700));
        background3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        picfood1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\foodpic15.jpg")); // NOI18N
        background3.add(picfood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 500, 320));

        namefood1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namefood1.setForeground(new java.awt.Color(255, 102, 51));
        namefood1.setText("Steak");
        background3.add(namefood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 300, 30));

        cost1.setBackground(new java.awt.Color(204, 0, 51));
        cost1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cost1.setForeground(new java.awt.Color(255, 255, 255));
        cost1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cost1.setText("150.000");
        cost1.setOpaque(true);
        background3.add(cost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 90, 30));
        background3.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 70, 30));

        number.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        number.setForeground(new java.awt.Color(255, 102, 51));
        number.setText("Number:");
        background3.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 60, 30));

        addcart.setBackground(new java.awt.Color(255, 102, 51));
        addcart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addcart.setForeground(new java.awt.Color(255, 255, 255));
        addcart.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Cart-add-icon.png")); // NOI18N
        addcart.setText("ADD TO CART");
        addcart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcartMouseClicked(evt);
            }
        });
        background3.add(addcart, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 290, 40));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(60, 63, 65));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("This is a European dish but slightly modified to suit the quality of beef, Vietnamese taste, quick and simple processing, but very nutritious.");
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        background3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 500, 130));

        jScrollPane1.setViewportView(background3);

        background2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        background.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 710, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    public void changecolorLable(JLabel label, Color rand) {
        label.setBackground(rand);
    }

    public void clickmenu(JPanel h1, JPanel h2, int numberbool) {
        if (numberbool == 1) {
            h1.setBackground(new Color(51, 51, 51));
            h2.setBackground(new Color(255, 102, 51));
        } else {
            h1.setBackground(new Color(255, 102, 51));
            h2.setBackground(new Color(51, 51, 51));
        }
    }

    public void changeimage(JLabel button, String resourcheimg) {
        button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button.setIcon(new javax.swing.ImageIcon(resourcheimg));
    }

    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button) {
        if (dashboard == true) {
            menushowhide.setPreferredSize(new Dimension(250, menushowhide.getHeight()));
            changeimage(button, "C:\\Users\\ACER\\Downloads\\white-down-arrow-png-2-300x300.png");
        } else {
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(button, "C:\\Users\\ACER\\Downloads\\PinClipart.com_cempasuchil-clipart_1812493.png");
            changecolor(hidenmenu, new Color(255, 102, 51));
        }
    }

    public void hideshowsetting(JPanel menushowhide, boolean dashboard, JLabel button) {
        if (dashboard == true) {
            menushowhide.setPreferredSize(new Dimension(250, menushowhide.getHeight()));
            changeimage(button, "C:\\Users\\ACER\\Downloads\\white-down-arrow-png-2-300x300.png");
        } else {
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(button, "C:\\Users\\ACER\\Downloads\\—Pngtree—settings icon_4479688 (1).png");
            changecolor(setting, new Color(255, 102, 51));
        }
    }
    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        dispose();
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered

        changeimage(back, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\backblack.png");
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        changeimage(back, "C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\back.png");
    }//GEN-LAST:event_backMouseExited

    private void addcartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcartMouseClicked
        try {

            String sql = "Insert into Cart (ID_Food,Number,Cost,FoodName) values ((SELECT ID_Food from food where FoodName = '"
                    + namefood1.getText() + "'),'" + jSpinner1.getValue() + "','"
                    + cost1.getText() + "','"+namefood1.getText()+"')";
            System.out.println(sql);
            int record = executeDB(sql);
            if (record > 0) {
                JOptionPane.showMessageDialog(null, "Add to cart successfully");
            }
        } catch (Exception e2) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_addcartMouseClicked

    private void buttonhidenmenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonhidenmenu1MouseClicked

    private void buttonhidenmenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonhidenmenu1MouseEntered

    private void buttonhidenmenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonhidenmenu1MouseExited

    private void buttonsetting1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsetting1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonsetting1MouseClicked

    private void buttonsetting1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsetting1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonsetting1MouseEntered

    private void buttonsetting1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsetting1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonsetting1MouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        dispose();
        InforInter infor = new InforInter();
        infor.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        changecolorLable(logout, new Color(204, 0, 51));

    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited

        changecolorLable(logout, new Color(51, 51, 51));
    }//GEN-LAST:event_logoutMouseExited

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        dispose();
        changepassword change = new changepassword();
        change.setVisible(true);
    }//GEN-LAST:event_accountMouseClicked

    private void accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseEntered
        changecolorLable(account, new Color(204, 0, 51));
    }//GEN-LAST:event_accountMouseEntered

    private void accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseExited
        changecolorLable(account, new Color(51, 51, 51));
    }//GEN-LAST:event_accountMouseExited

    private void buttonhidenmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenuMouseClicked
        clickmenu(hidenmenu, setting, 1);
        if (a == true) {
            hideshow(menu, a, buttonhidenmenu);
            SwingUtilities.updateComponentTreeUI(this);
            a = false;

            sett.setPreferredSize(new Dimension(50, sett.getHeight()));
            changeimage(buttonsetting, "C:\\Users\\ACER\\Downloads\\—Pngtree—settings icon_4479688 (1).png");
            changecolor(setting, new Color(255, 102, 51));
            SwingUtilities.updateComponentTreeUI(this);
        } else {
            hideshow(menu, a, buttonhidenmenu);
            SwingUtilities.updateComponentTreeUI(this);
            a = true;
        }
    }//GEN-LAST:event_buttonhidenmenuMouseClicked

    private void buttonhidenmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenuMouseEntered
        changecolor(linehidenmenu, Color.red);
    }//GEN-LAST:event_buttonhidenmenuMouseEntered

    private void buttonhidenmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenuMouseExited
        changecolor(linehidenmenu, new Color(255, 102, 51));
    }//GEN-LAST:event_buttonhidenmenuMouseExited

    private void buttonsettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsettingMouseClicked
        clickmenu(setting, hidenmenu, 1);
        if (b == true) {
            hideshowsetting(sett, b, buttonsetting);
            SwingUtilities.updateComponentTreeUI(this);
            b = false;

            menu.setPreferredSize(new Dimension(50, menu.getHeight()));
            changeimage(buttonhidenmenu, "C:\\Users\\ACER\\Downloads\\PinClipart.com_cempasuchil-clipart_1812493.png");
            changecolor(hidenmenu, new Color(255, 102, 51));

        } else {
            hideshowsetting(sett, b, buttonsetting);
            SwingUtilities.updateComponentTreeUI(this);
            b = true;
        }
    }//GEN-LAST:event_buttonsettingMouseClicked

    private void buttonsettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsettingMouseEntered
        changecolor(linesetting, Color.red);
    }//GEN-LAST:event_buttonsettingMouseEntered

    private void buttonsettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsettingMouseExited
        changecolor(linesetting, new Color(255, 102, 51));
    }//GEN-LAST:event_buttonsettingMouseExited

    private void linechatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linechatMouseEntered

    }//GEN-LAST:event_linechatMouseEntered

    private void linechatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linechatMouseExited

    }//GEN-LAST:event_linechatMouseExited

    private void buttonhidenmenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu2MouseClicked
        ChatCustomClient chatclient = new ChatCustomClient();
        chatclient.setVisible(true);

    }//GEN-LAST:event_buttonhidenmenu2MouseClicked

    private void buttonhidenmenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu2MouseEntered
        changecolor(linechat, Color.red);
        changeimage(buttonhidenmenu2, "C:\\Users\\ACER\\Downloads\\chat-icon (1).png");
    }//GEN-LAST:event_buttonhidenmenu2MouseEntered

    private void buttonhidenmenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidenmenu2MouseExited
        changecolor(linechat, new Color(255, 102, 51));
        changeimage(buttonhidenmenu2, "C:\\Users\\ACER\\Downloads\\chat-icon.png");
    }//GEN-LAST:event_buttonhidenmenu2MouseExited

    private void contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseClicked
        dispose();
        contact con = new contact();
        con.setVisible(true);
    }//GEN-LAST:event_contactMouseClicked

    private void contactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseEntered
        changecolorLable(contact, new Color(204, 0, 51));
    }//GEN-LAST:event_contactMouseEntered

    private void contactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseExited
        changecolorLable(contact, new Color(51, 51, 51));
    }//GEN-LAST:event_contactMouseExited

    private void gomenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gomenuMouseClicked
        dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_gomenuMouseClicked

    private void gomenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gomenuMouseEntered
        changecolorLable(gomenu, new Color(204, 0, 51));
    }//GEN-LAST:event_gomenuMouseEntered

    private void gomenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gomenuMouseExited
        changecolorLable(gomenu, new Color(51, 51, 51));
    }//GEN-LAST:event_gomenuMouseExited

    private void homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseClicked
        dispose();
        FoodHomePage food = new FoodHomePage();
        food.setVisible(true);
    }//GEN-LAST:event_homepageMouseClicked

    private void homepageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseEntered
        changecolorLable(homepage, new Color(204, 0, 51));
    }//GEN-LAST:event_homepageMouseEntered

    private void homepageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseExited
        changecolorLable(homepage, new Color(51, 51, 51));
    }//GEN-LAST:event_homepageMouseExited

    private void cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseClicked
        dispose();
        cart cart = new cart();
        cart.setVisible(true);
    }//GEN-LAST:event_cartMouseClicked

    private void cartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseEntered
        changecolorLable(cart, new Color(204, 0, 51));
    }//GEN-LAST:event_cartMouseEntered

    private void cartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseExited
        changecolorLable(cart, new Color(51, 51, 51));
    }//GEN-LAST:event_cartMouseExited

    private void favorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favorMouseClicked
        dispose();
        Favorite f = new Favorite();
        f.setVisible(true);
    }//GEN-LAST:event_favorMouseClicked

    private void favorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favorMouseEntered
        changecolorLable(favor, new Color(204, 0, 51));
    }//GEN-LAST:event_favorMouseEntered

    private void favorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favorMouseExited

        changecolorLable(favor, new Color(51, 51, 51));
    }//GEN-LAST:event_favorMouseExited

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public int executeDB(String sql) {
        int record = 0;// number of records have been changed in db
        try {
            connect();
            Statement stmt = (Statement) conn.createStatement();
            record = stmt.executeUpdate(sql);
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
        }
        return record;
    }

    public static void connect() {
        try {
            String sqlServer = "jdbc:sqlserver://LAPTOP-EUQVAG1I\\SQLEXPRESS;databasename=GLFood;user=sa;password=123456789";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection(sqlServer);
            Statement stm = conn.createStatement();
        } catch (Exception e) {
            // TODO: handle exception
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sell15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sell15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sell15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sell15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sell15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Order;
    private javax.swing.JLabel account;
    private javax.swing.JButton addcart;
    private javax.swing.JLabel back;
    private javax.swing.JPanel background;
    private javax.swing.JPanel background2;
    private javax.swing.JPanel background3;
    private javax.swing.JLabel buttonhidenmenu;
    private javax.swing.JLabel buttonhidenmenu1;
    private javax.swing.JLabel buttonhidenmenu2;
    private javax.swing.JLabel buttonsetting;
    private javax.swing.JLabel buttonsetting1;
    private javax.swing.JLabel cart;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel cost1;
    private javax.swing.JLabel favor;
    private javax.swing.JLabel gomenu;
    private javax.swing.JPanel header2;
    private javax.swing.JPanel headerMenu;
    private javax.swing.JPanel hidenmenu;
    private javax.swing.JPanel hidenmenu1;
    private javax.swing.JLabel homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel linechat;
    private javax.swing.JPanel linehidenmenu;
    private javax.swing.JPanel linehidenmenu1;
    private javax.swing.JPanel linesetting;
    private javax.swing.JPanel linesetting1;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JPanel menuIcon1;
    private javax.swing.JPanel menuhide;
    private javax.swing.JPanel menuhide1;
    private javax.swing.JLabel namefood1;
    private javax.swing.JLabel number;
    private javax.swing.JLabel picfood1;
    private javax.swing.JPanel sett;
    private javax.swing.JPanel setting;
    private javax.swing.JPanel setting1;
    // End of variables declaration//GEN-END:variables
}
