/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package glfood;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.List;
import java.sql.DriverManager;
import java.text.Normalizer;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordretype = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        jPasswordFieldRetype = new javax.swing.JPasswordField();
        password = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        phone = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        Logo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordretype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordretype.setForeground(new java.awt.Color(255, 153, 0));
        passwordretype.setText("Retype your password");
        getContentPane().add(passwordretype, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 170, 30));
        passwordretype.getAccessibleContext().setAccessibleName("");

        jTextFieldUsername.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldUsername.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldUsername.setText("Enter your user name");
        getContentPane().add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 230, 30));

        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 153, 0));
        username.setText("User Name");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, 30));

        jPasswordFieldRetype.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldRetype.setText("jPasswordField1");
        jPasswordFieldRetype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRetypeActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldRetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 230, 30));

        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 153, 0));
        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 80, 30));

        jPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField.setText("jPasswordField1");
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 230, 30));

        phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 153, 0));
        phone.setText("Phone Number");
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 120, 30));

        jTextFieldPhone.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPhone.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPhone.setText("Enter your phone number");
        getContentPane().add(jTextFieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 200, 30));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 153, 0));
        email.setText("Email");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 120, 30));

        jTextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEmail.setText("Enter your email");
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 230, 30));

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\Screenshot 2022-05-21 023335.png")); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, 70));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 200, 40));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Dropbox\\PC\\Downloads\\GLFOODLogin.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldRetypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRetypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRetypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextFieldUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please input your username");
        } else {
            if (jPasswordField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please input your password");
            } else {
                if (jPasswordFieldRetype.getText().equals("") || jPasswordField.getText() == jPasswordFieldRetype.getText()) {
                    JOptionPane.showMessageDialog(this, "Please retype your password");
                } else {
                    if (jTextFieldPhone.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Please input your phone number");
                    } else {
                        try {
                            String sqlServer = "jdbc:sqlserver://LAPTOP-EUQVAG1I\\SQLEXPRESS;databasename=GLFood;user=sa;password=123456789";
                            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                            Connection connection = DriverManager.getConnection(sqlServer);
                            Statement stm = connection.createStatement();
                            String insert = "Insert into AccountGL values('" + jTextFieldUsername.getText() + "','"
                                    + jPasswordField.getText() + "','" + jTextFieldPhone.getText() + "','"
                                    + jTextFieldEmail.getText() + "')";

                            String sql = "SELECT * FROM AccountGL WHERE Username = ?";

                            PreparedStatement ps = connection.prepareStatement(sql);
                            ps.setString(1, jTextFieldUsername.getText());
                            ResultSet rs = ps.executeQuery();

                            if (rs.next()) {
                                JOptionPane.showMessageDialog(this, "Error creating new account! The account name is already there!");
                            } else {
                                int record = stm.executeUpdate(insert);
                                JOptionPane.showMessageDialog(this, "Create new account successfully!");
                                dispose();

                            }
                        } catch (Exception e2) {
                            e2.printStackTrace();
                        }

                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignUp sign = new SignUp();
                sign.setVisible(true);
                sign.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel background;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordFieldRetype;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JLabel password;
    private javax.swing.JLabel passwordretype;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
